### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by bymayanksingh**

### CODE REVIEW

**Comment by quozl** [comment]
Please don't waste time creating an issue that you open a pull request for.  It is redundant and creates notification noise.  See our guide to contributing again.

**Comment by bymayanksingh** [comment]
Thanks @quozl, actually the issue #5 was opened by @Aniket21mathur, I just responded in return to it.

**Comment by quozl** [comment]
Thanks, my mistake.  I got confused.  Instead, I should have said; "Please link your pull request to the issue so that when we merge the pull request the issue is automatically closed."

**Comment by bymayanksingh** [comment]
Yes, I will remember that. :+1: 

> Thanks, my mistake. I got confused. Instead, I should have said; "Please link your pull request to the issue so that when we merge the pull request the issue is automatically closed."

**Pull request merged**
